---
title: "STOR 665 HW 7"
author: "Brian N. White"
date: "4/23/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MEMSS)
library(lme4)
```

### Problem 7

### (a)

Explain the data briefly.
```{r load data, examine structure}
#load data
ergoStool <- ergoStool

#examine the data structure
str(ergoStool)
```
```{r summary}
#data summary
summary(ergoStool)
```
Inspection of the contingency table below reveals that the factors 'Type' and 'Subject' are completely crossed (i.e. there is at least one observation for each combination of factor levels). Further, this is an unreplicated design.
```{r}
xtabs(~Type + Subject, ergoStool)
```
### (b)

```{r}
#determine the average effort for each level of the factor Subject
ergoStool %>%
  group_by(Subject) %>%
  summarize(avg_effort=mean(effort)) -> avg_effort_df

ergoStool %>% 
  mutate(avg_effort=rep(avg_effort_df$avg_effort, each=4, times=1)) %>%
  mutate(Subject=fct_reorder(Subject, avg_effort)) %>%
  ggplot(aes(x=Subject, y=effort, shape=Type, color=Type)) +
  geom_point() +
  geom_line(aes(x=Subject, y=effort, group=Type, color=Type, linetype=Type))

```

### (c)

```{r}

```

